version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      pip:
        applies-to: version-updates
        patterns: 
        - "*"
        update-types:
        - "minor"
        - "patch"
